#ifndef LOITERBOT_TEST_CONSTANTS_HPP
#define LOITERBOT_TEST_CONSTANTS_HPP

const double LASER_ANGLE_MINIMUM = -1.396263;
const double LASER_ANGLE_INCREMENT = 0.004370;

#endif  //LOITERBOT_TEST_CONSTANTS_HPP
